<?php

namespace simply_static_pro\commands\deployment;

use simply_static_pro\commands\Update_Command;


class Github extends Update_Command {

	protected $section = 'deployment';

	protected $name = 'github';

	protected $option_name = '';

	protected $description = 'Setup Github.';

	public function get_synopsis() {

		$synopsis = [

		];

		return array_merge( $synopsis, parent::get_synopsis() ); // TODO: Change the autogenerated stub
	}

	/**
	 * Run
	 *
	 * @param $args
	 * @param $options
	 *
	 * @return void
	 */
	public function run( $args, $options ) {
		\WP_CLI::line( 'Feature coming soon' );
	}
}