<?php

namespace simply_static_pro\commands\general;

use simply_static_pro\commands\Update_Command;

class Local_Directory extends Update_Command {

	protected $section = 'general';

	protected $name = 'local_dir';

	protected $option_name = 'local_dir';

	protected $description = 'Update Local Directory path. Used when delivery_method is set to local.';

	public function get_synopsis() {

		$synopsis = [
			array(
				'type'        => 'positional',
				'name'        => 'value',
				'description' => "The value to save as Local directory",
				'optional'    => false,
				'repeating'   => false,
			)
		];

		return array_merge( $synopsis, parent::get_synopsis() ); // TODO: Change the autogenerated stub
	}

	/**
	 * Run
	 *
	 * @param $args
	 * @param $options
	 *
	 * @return void
	 */
	public function run( $args, $options ) {
		$update_value = $args[0];

		$this->update( $update_value );
		\WP_CLI::success( 'Updated!' );
	}
}